---
name: NetBird
version: dev
slug: netbird
description: Connect your devices into a single secure private WireGuard®-based mesh network.
url: https://github.com/lfarkas/addon-netbird
codenotary: lfarkas@lfarkas.org
startup: services
panel_icon: mdi:vpn
#ingress: true
#ngress_port: 0
#ingress_stream: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
host_dbus: true
privileged:
  - NET_ADMIN
map:
  - config:rw
options:
  admin_url: ""
  management_url: ""
  setup_key: ""
  hostname: ""
schema:
  admin_url: str
  management_url: str
  setup_key: str
  hostname: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
