---
name: NetBird
version: 0.21.1
slug: netbird
description: Connect your devices into a single secure private WireGuard®-based mesh network with SSO/MFA and simple access controls.
url: https://github.com/lfarkas/addon-netbird
codenotary: codenotary@frenck.dev
startup: services
panel_icon: mdi:vpn
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
privileged:
  - NET_ADMIN
map:
  - config:rw
options:
  admin_url: ""
  management_url: ""
  setup_key: ""
  hostname: ""
schema:
  admin_url: str
  management_url: str
  setup_key: str
  hostname: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
